-- Questions to Answers

--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the avg purchase amount?
select customer_id, discount_applied, purchase_amount
from customer
where discount_applied = 'Yes'
and purchase_amount >= (
select avg(purchase_amount) as [avg purchase]
from customer)

--Q3. Which are the top 5 products with the highest avg review rating?

select top 8 item_purchased, round(avg(review_rating),2) as [avg rating]
from customer
group by item_purchased
order by [avg rating] desc

--Q4. Compare the avg Purchase Amounts between Standard and Express Shipping.

select shipping_type, avg(purchase_amount) as [avg purchase]
from customer
where shipping_type in ('Express', 'Standard')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare avg spend and total revenue between subcribers and non-subs.

select subscription_status, 
count(customer_id) as [customers], 
avg(purchase_amount) as [avg purchase], 
sum(purchase_amount) as [total revenue]
from customer
group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
	-- You’re ranking the top 5 products by the percentage of times customers bought them with a discount.
select top 5 item_purchased,
sum(case when discount_applied = 'Yes' then 1 else 0 end) as [discounted items],
count(*) as [ttl items],
cast(round(100.0 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as decimal(5,2)) as [% of x bought w/ discount]
from customer
group by item_purchased
order by [% of x bought w/ discount] desc



--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
-- and show the count of each segment.

with customer_type as (
select customer_id, previous_purchases, 
	case 
		when previous_purchases = 1 then 'New'
		when previous_purchases between 2 and 10 then 'Returning'
		else 'Loyal'
	end as customer_segment
from customer)

select customer_segment, 
COUNT(customer_segment) as [number of customers]
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category?

with jack as (
select category, item_purchased, count(customer_id) as [total purchase],
row_number() over (partition by category order by category, count(customer_id) desc) as [total orders]
from customer
group by category, item_purchased)

select *
from jack 
where [total orders] < 4

--Q9. Are customers who are repeat buys (more than 5 previous purchases) also likely to subscribe?

select (case when previous_purchases > 5 then 'repeat' else 'nah' end) as typeshii,
[subscription_status],
count([subscription_status]) as subs
from customer
where (case when previous_purchases > 5 then 'repeat' else 'nah' end) = 'repeat'
group by (case when previous_purchases > 5 then 'repeat' else 'nah' end), [subscription_status]

--Q10. What is the revenue contribution of each age group?

select age_group, sum(purchase_amount) as [revenue]
from customer
group by age_group
order by revenue desc




